services:
  tchoutchou-api:
    image: ghcr.io/thomas-god/tchoutchou-app:main
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.services.tchoutchou-api.loadbalancer.server.port=3001'
      - 'traefik.http.routers.tchoutchou-api.rule=Host(`train.trackforge.fr`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.tchoutchou-api.entrypoints=websecure'
      - 'traefik.http.routers.tchoutchou-api.tls.certresolver=myresolver'

      - 'traefik.docker.network=traefik-public'
    environment:
      SERVER_PORT: 3001
      ALLOW_ORIGIN: https://train.trackforge.fr
      DATA_LOCATION: /data
      NOMINATIM_URL_FILE: /run/secrets/tchoutchou_nominatim_url

    networks:
      - traefik-public

    secrets:
      - tchoutchou_nominatim_url

    volumes:
      - tchoutchou_data:/data

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.50'
          memory: 1G
      update_config:
        order: start-first

  tchoutchou:
    image: ghcr.io/thomas-god/tchoutchou-client:main
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.services.tchoutchou.loadbalancer.server.port=3000'
      - 'traefik.http.routers.tchoutchou.rule=Host(`train.trackforge.fr`)'
      - 'traefik.http.routers.tchoutchou.entrypoints=websecure'
      - 'traefik.http.routers.tchoutchou.tls.certresolver=myresolver'

      - 'traefik.docker.network=traefik-public'
    environment:
      BACKEND_URL: http://tchoutchou-api:3001

    networks:
      - traefik-public

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
      update_config:
        order: start-first

secrets:
  tchoutchou_nominatim_url:
    external: true

networks:
  traefik-public:
    external: true

volumes:
  tchoutchou_data:
